In [ ]:
import pandas as pd
import numpy as np
import re
from google.colab import files

In [ ]:
file_path = r"/content/sales.xlsx"
df = pd.read_excel(file_path)

In [ ]:
df

,No. Urut,Ref,Tgl Ref,No. Ref,No. Dok Ref,Kode Cust,Nama Cust,Alamat Cust,Kode Panel,Nama Panel,...,Hrg Unit Riil(Mu),Total Riil(Mu),Subtot Disc Riil(Mu),Subtot Riil(Mu),Disc Akh(Mu),Subtot Net(Mu),Pjk(Mu),Subtot Net Pjk(Mu),Kode Kota,Nama Kota
0,81.0,FJ,2025-05-02,2505-MX0005,2505-MX0005,C-CV--003,CV SUPER MART SENTOSA,URIMESING,NaN,NaN,...,27871.62,222972.97,0.0,222972.97,0,222972.97,24527.03,247500.0,AMBON,AMBON
1,82.0,FJ,2025-05-02,2505-MX0005,2505-MX0005,C-CV--003,CV SUPER MART SENTOSA,URIMESING,NaN,NaN,...,7700.00,23100.00,0.0,23100.00,0,23100.00,2541.00,25641.0,AMBON,AMBON
2,83.0,FJ,2025-05-02,2505-MX0005,2505-MX0005,C-CV--003,CV SUPER MART SENTOSA,URIMESING,NaN,NaN,...,7700.00,23100.00,0.0,23100.00,0,23100.00,2541.00,25641.0,AMBON,AMBON
3,84.0,FJ,2025-05-02,2505-MX0005,2505-MX0005,C-CV--003,CV SUPER MART SENTOSA,URIMESING,NaN,NaN,...,124324.32,124324.32,0.0,124324.32,0,124324.32,13675.68,138000.0,AMBON,AMBON
4,94.0,FJ,2025-05-02,2505-MX0004,2505-MX0004,CUST0066,SANDY,PASSO,NaN,NaN,...,92162.16,92162.16,0.0,92162.16,0,92162.16,10137.84,102300.0,AMBON,AMBON
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,147.0,FJ,2025-05-15,2505-MX0349,2505-MX0349,DAMAI-SEJAHTERA,CV. DAMAI SEJAHTERA,JL WOLTER MONGIN SIDI,NaN,NaN,...,124324.32,248648.65,0.0,248648.65,0,248648.65,27351.35,276000.0,AMBON,AMBON
201,148.0,FJ,2025-05-15,2505-MX0349,2505-MX0349,DAMAI-SEJAHTERA,CV. DAMAI SEJAHTERA,JL WOLTER MONGIN SIDI,NaN,NaN,...,210810.81,210810.81,0.0,210810.81,0,210810.81,23189.19,234000.0,AMBON,AMBON
202,149.0,FJ,2025-05-15,2505-MX0349,2505-MX0349,DAMAI-SEJAHTERA,CV. DAMAI SEJAHTERA,JL WOLTER MONGIN SIDI,NaN,NaN,...,124324.32,124324.32,0.0,124324.32,0,124324.32,13675.68,138000.0,AMBON,AMBON
203,150.0,FJ,2025-05-15,2505-MX0349,2505-MX0349,DAMAI-SEJAHTERA,CV. DAMAI SEJAHTERA,JL WOLTER MONGIN SIDI,NaN,NaN,...,15502.97,31005.95,0.0,31005.95,0,31005.95,3410.65,34416.6,AMBON,AMBON
204,152.0,FJ,2025-05-15,2505-MX0333,2505-MX0333,FJ0001,FAJIR,PASAR RUMAH TIGA,NaN,NaN,...,92162.16,184324.32,0.0,184324.32,0,184324.32,20275.68,204600.0,AMBON,AMBON

# Data Cleaning

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 48 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   No. Urut              205 non-null    float64
 1   Ref                   205 non-null    object
 2   Tgl Ref               205 non-null    datetime64[ns]
 3   No. Ref               205 non-null    object
 4   No. Dok Ref           205 non-null    object
 5   Kode Cust             205 non-null    object
 6   Nama Cust             205 non-null    object
 7   Alamat Cust           205 non-null    object
 8   Kode Panel            0 non-null      float64
 9   Nama Panel            0 non-null      float64
 10  Kode Sales            205 non-null    object
 11  Nama Sales            205 non-null    object
 12  Keterangan            30 non-null     object
 13  Pajak                 205 non-null    object
 14  Kategori Pjk          205 non-null    object
 15  Kode Barang           205 non-null    object
 16  Nama Jns Brg          0 non-null      float64
 17  Ket Ref               205 non-null    object
 18  Qty                   205 non-null    int64
 19  Sat                   205 non-null    object
 20  Qty Std               205 non-null    int64
 21  Sat Std               205 non-null    object
 22  Harga (+)             205 non-null    int64
 23  Harga Sbl (+)         205 non-null    float64
 24  Harga Unit(Mu)        205 non-null    float64
 25  Total(MU)             205 non-null    float64
 26  Disc. 1 (%)           205 non-null    int64
 27  Disc. 1 (MU)          205 non-null    float64
 28  Disc. 2 (%)           205 non-null    float64
 29  Disc. 2 (MU)          205 non-null    float64
 30  Disc. 3 (%)           205 non-null    int64
 31  Disc. 3 (MU)          205 non-null    int64
 32  Disc. 4 (MU)          205 non-null    int64
 33  Disc. 5 (%)           205 non-null    int64
 34  Disc. 5 (MU)          205 non-null    int64
 35  Disc. 6 (MU)          205 non-null    int64
 36  Subtot Disc(Mu)       205 non-null    float64
 37  Subtot(Mu)            205 non-null    float64
 38  Hrg Unit Riil(Mu)     205 non-null    float64
 39  Total Riil(Mu)        205 non-null    float64
 40  Subtot Disc Riil(Mu)  205 non-null    float64
 41  Subtot Riil(Mu)       205 non-null    float64
 42  Disc Akh(Mu)          205 non-null    int64
 43  Subtot Net(Mu)        205 non-null    float64
 44  Pjk(Mu)               205 non-null    float64
 45  Subtot Net Pjk(Mu)    205 non-null    float64
 46  Kode Kota             200 non-null    object
 47  Nama Kota             200 non-null    object
dtypes: datetime64[ns](1), float64(19), int64(11), object(17)
memory usage: 77.0+ KB

## Cleansing column "No. Urut"

In [ ]:
df["No. Urut"] = df["No. Urut"].astype(str).str.replace(r"\.$", "", regex=True)
df["No. Urut"] = pd.to_numeric(df["No. Urut"], errors="coerce").astype("Int64")

## Cleansing column "Kode Sales"

In [ ]:
df[['Kode Sales', 'Nama Sales']].drop_duplicates().sort_values(['Kode Sales', 'Nama Sales'])

    Kode Sales   Nama Sales
31        EL01  Erwin Taneo
113       SL10  Erwin Taneo
10        SL10       FENDRY
4         SL12  Erwin Taneo
0         SL12       FENDRY

In [ ]:
# Because the sales code values are not unique and some codes are associated with more than one sales name, the sales codes need to be standardised for consistency.
# ensured each sales code uniquely maps to one salesperson.
df['Kode Sales'] = np.where(
    df['Nama Sales'] == 'Erwin Taneo', 'SL12',
    np.where(df['Nama Sales'] == 'FENDRY', 'SL10', df['Kode Sales']))
df[['Kode Sales', 'Nama Sales']].drop_duplicates().sort_values(['Kode Sales', 'Nama Sales'])

  Kode Sales   Nama Sales
0       SL10       FENDRY
4       SL12  Erwin Taneo

## Cleansing column "Kode Barang"

In [ ]:
df[['Kode Barang', 'Sat', 'Sat Std']].drop_duplicates().sort_values(['Kode Barang', 'Sat', 'Sat Std'])

       Kode Barang  Sat Sat Std
56      4100000002  CRT     PCS
2       4100000002  PCS     PCS
153     4100000009  CRT     BTL
29      4100000047  BTL     BTL
164     4100000047  CRT     BTL
..             ...  ...     ...
152  4100000964.GT  CRT     PCS
17   4100000964.GT  RCG     PCS
11   4100001079NEW  PCS     PCS
27   4100001080NEW  PCS     PCS
4      4100001212.  CRT     PCS

[73 rows x 3 columns]

In [ ]:
# standardization "Kode Barang"
def clean_kode_barang(kode):
    if pd.isna(kode):
        return None
    kode_str = str(kode)
    kode_clean = re.sub(r'[^\d]', '', kode_str)
    return kode_clean

df['Kode Barang'] = df['Kode Barang'].apply(clean_kode_barang)
df[['Kode Barang', 'Sat', 'Sat Std']].drop_duplicates().sort_values(['Kode Barang', 'Sat', 'Sat Std'])

    Kode Barang  Sat Sat Std
56   4100000002  CRT     PCS
2    4100000002  PCS     PCS
153  4100000009  CRT     BTL
29   4100000047  BTL     BTL
164  4100000047  CRT     BTL
..          ...  ...     ...
136  4100001396  CRT     PCS
18   4100001396  RTG     PCS
161  4100001397  CRT     PCS
19   4100001397  RTG     PCS
75   4100001425  BAL     PAK

[73 rows x 3 columns]

# Download Clean Data

In [ ]:
df_sorted = df.sort_values(by="No. Urut", ascending=True).reset_index(drop=True)

In [ ]:
df_sorted

,No. Urut,Ref,Tgl Ref,No. Ref,No. Dok Ref,Kode Cust,Nama Cust,Alamat Cust,Kode Panel,Nama Panel,...,Hrg Unit Riil(Mu),Total Riil(Mu),Subtot Disc Riil(Mu),Subtot Riil(Mu),Disc Akh(Mu),Subtot Net(Mu),Pjk(Mu),Subtot Net Pjk(Mu),Kode Kota,Nama Kota
0,1,FJ,2025-05-05,2505-MX0065,2505-MX0065,110--KIO0541,RAFAEL,SETIA BUDI,NaN,NaN,...,92162.16,460810.81,0.0,460810.81,0,460810.81,50689.19,511500.00,AMBON,AMBON
1,2,FJ,2025-05-05,2505-MX0065,2505-MX0065,110--KIO0541,RAFAEL,SETIA BUDI,NaN,NaN,...,92162.16,460810.81,0.0,460810.81,0,460810.81,50689.19,511500.00,AMBON,AMBON
2,3,FJ,2025-05-13,2505-MX0279,2505-MX0279,104-CAMPINA-CAM0001,PINK TAWIRI,SAMPING J & J TAWIRI,NaN,NaN,...,92162.16,184324.32,0.0,184324.32,0,184324.32,20275.68,204600.00,AMBON,AMBON
3,4,FJ,2025-05-13,2505-MX0279,2505-MX0279,104-CAMPINA-CAM0001,PINK TAWIRI,SAMPING J & J TAWIRI,NaN,NaN,...,92162.16,92162.16,0.0,92162.16,0,92162.16,10137.84,102300.00,AMBON,AMBON
4,5,FJ,2025-05-07,2505-MX0115,2505-MX0115,110--ADE0624,ADE LALI PASSO,DEPAN LAP. PERIKANAN,NaN,NaN,...,15315.32,15315.32,0.0,15315.32,0,15315.32,1684.68,17000.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,FJ,2025-05-08,2505-MX0156,2505-MX0156,YON--0001,WALE,BENTAS,NaN,NaN,...,92162.16,92162.16,0.0,92162.16,0,92162.16,10137.84,102300.00,AMBON,AMBON
201,202,FJ,2025-05-08,2505-MX0156,2505-MX0156,YON--0001,WALE,BENTAS,NaN,NaN,...,92162.16,92162.16,0.0,92162.16,0,92162.16,10137.84,102300.00,AMBON,AMBON
202,203,FJ,2025-05-08,2505-MX0156,2505-MX0156,YON--0001,WALE,BENTAS,NaN,NaN,...,81081.08,81081.08,0.0,81081.08,0,81081.08,8918.92,90000.00,AMBON,AMBON
203,204,FJ,2025-05-08,2505-MX0156,2505-MX0156,YON--0001,WALE,BENTAS,NaN,NaN,...,90090.16,90090.16,0.0,90090.16,0,90090.16,9909.92,100000.08,AMBON,AMBON
204,205,FJ,2025-05-08,2505-MX0156,2505-MX0156,YON--0001,WALE,BENTAS,NaN,NaN,...,92162.16,92162.16,0.0,92162.16,0,92162.16,10137.84,102300.00,AMBON,AMBON

In [ ]:
df_sorted.to_csv("sales_clean.csv", index=False)
files.download('sales_clean.csv')